import { TEMPLATE_IDS } from './templates/registry'

export type TemplateId = (typeof TEMPLATE_IDS)[number]

export interface TemplateFontRoleDefinition {
  readonly id: string
  readonly label: string
  readonly description: string
  readonly cssVar: string
  readonly defaultValue: number
  readonly options: readonly number[]
}

export interface TemplateThemeTokens {
  readonly '--template-board-bg': string
  readonly '--template-board-surface': string
  readonly '--template-board-surface-soft': string
  readonly '--template-board-border': string
  readonly '--template-board-border-strong': string
  readonly '--template-board-text': string
  readonly '--template-board-muted': string
  readonly '--template-board-subtitle': string
  readonly '--template-board-shadow': string
  readonly '--template-card-bg': string
  readonly '--template-card-border': string
  readonly '--template-card-shadow': string
  readonly '--template-card-surface': string
  readonly '--template-card-surface-border': string
  readonly '--template-card-divider': string
  readonly '--template-primary-start': string
  readonly '--template-primary-end': string
  readonly '--template-primary-text': string
  readonly '--template-primary-border': string
  readonly '--template-primary-soft': string
  readonly '--template-secondary-start': string
  readonly '--template-secondary-end': string
  readonly '--template-secondary-text': string
  readonly '--template-secondary-border': string
  readonly '--template-secondary-soft': string
  readonly '--template-pill-start': string
  readonly '--template-pill-end': string
  readonly '--template-pill-text': string
}

export interface TemplateThemeDefinition {
  readonly id: string
  readonly label: string
  readonly description: string
  readonly previewColors: readonly string[]
  readonly tokens: TemplateThemeTokens
}

export interface TemplateStyleDefinition {
  readonly id: TemplateId
  readonly label: string
  readonly defaultThemeId: string
  readonly fontRoles: readonly TemplateFontRoleDefinition[]
  readonly themes: readonly TemplateThemeDefinition[]
}

const FONT_SIZE_OPTIONS = [12, 14, 16, 18, 20, 24, 28, 32] as const
const LARGE_FONT_SIZE_OPTIONS = [16, 18, 20, 24, 28, 32] as const

const EXAM_RESULT_FONT_ROLES: readonly TemplateFontRoleDefinition[] = [
  {
    id: 'header-bracket',
    label: '裝飾文字',
    description: '頁首中括號內的短句或校訓感標語。',
    cssVar: '--template-header-bracket-size',
    defaultValue: 14,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'board-title',
    label: '主標題',
    description: '整張榮譽榜最主要的標題文字。',
    cssVar: '--template-board-title-size',
    defaultValue: 24,
    options: LARGE_FONT_SIZE_OPTIONS,
  },
  {
    id: 'board-subtitle',
    label: '副標題',
    description: '主標題下方的補充說明與祝賀文字。',
    cssVar: '--template-board-subtitle-size',
    defaultValue: 16,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-tag',
    label: '卡片標籤',
    description: '卡片頂端的小標籤，例如科目或分類。',
    cssVar: '--template-card-tag-size',
    defaultValue: 12,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-school',
    label: '卡片學校',
    description: '學生姓名上方的學校名稱。',
    cssVar: '--template-card-school-size',
    defaultValue: 12,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-name',
    label: '卡片姓名',
    description: '卡片中最醒目的學生姓名。',
    cssVar: '--template-card-name-size',
    defaultValue: 30,
    options: LARGE_FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-description',
    label: '卡片描述',
    description: '卡片底部的錄取學校或補充資訊。',
    cssVar: '--template-card-description-size',
    defaultValue: 14,
    options: FONT_SIZE_OPTIONS,
  },
]

const CLASS_RANKING_FONT_ROLES: readonly TemplateFontRoleDefinition[] = [
  {
    id: 'board-eyebrow',
    label: '抬頭文字',
    description: '主標題上方的短句或抬頭說明。',
    cssVar: '--template-board-eyebrow-size',
    defaultValue: 16,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'board-title',
    label: '主標題',
    description: '整張榜單最主要的標題文字。',
    cssVar: '--template-board-title-size',
    defaultValue: 24,
    options: LARGE_FONT_SIZE_OPTIONS,
  },
  {
    id: 'badge-label',
    label: '章節徽章',
    description: '校排榮譽、班排榮譽這類章節徽章。',
    cssVar: '--template-badge-label-size',
    defaultValue: 26,
    options: LARGE_FONT_SIZE_OPTIONS,
  },
  {
    id: 'section-subtitle',
    label: '章節英文副標',
    description: '每個章節下方的英文副標題。',
    cssVar: '--template-section-title-size',
    defaultValue: 16,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-head',
    label: '卡片標題',
    description: '每張排名卡片頂部的第幾名標題。',
    cssVar: '--template-card-head-size',
    defaultValue: 22,
    options: LARGE_FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-class',
    label: '班級膠囊',
    description: '卡片內圓角膠囊的班級號碼。',
    cssVar: '--template-card-class-size',
    defaultValue: 16,
    options: FONT_SIZE_OPTIONS,
  },
  {
    id: 'card-name',
    label: '卡片姓名',
    description: '每張卡片內最醒目的學生姓名。',
    cssVar: '--template-card-name-size',
    defaultValue: 26,
    options: LARGE_FONT_SIZE_OPTIONS,
  },
  {
    id: 'board-footer',
    label: '頁尾文字',
    description: '最底部重複顯示的榜單標題。',
    cssVar: '--template-board-footer-size',
    defaultValue: 16,
    options: FONT_SIZE_OPTIONS,
  },
]

const EXAM_RESULT_THEMES: readonly TemplateThemeDefinition[] = [
  {
    id: 'classic',
    label: '典藏金',
    description: '奶油紙色搭配沉穩金棕，保留最正式的金榜感。',
    previewColors: ['#fcf8f1', '#2f2418', '#c9962d'],
    tokens: {
      '--template-board-bg': '#fcf8f1',
      '--template-board-surface': '#ffffff',
      '--template-board-surface-soft': '#fffaf2',
      '--template-board-border': '#d6c7b5',
      '--template-board-border-strong': '#c8b59b',
      '--template-board-text': '#2f2418',
      '--template-board-muted': '#7d6a55',
      '--template-board-subtitle': '#9a7c52',
      '--template-board-shadow': 'rgba(68, 49, 27, 0.08)',
      '--template-card-bg': 'rgba(255, 255, 255, 0.55)',
      '--template-card-border': 'rgba(101, 75, 43, 0.12)',
      '--template-card-shadow': 'rgba(68, 49, 27, 0.1)',
      '--template-card-surface': 'rgba(255, 251, 244, 0.88)',
      '--template-card-surface-border': 'rgba(134, 104, 64, 0.1)',
      '--template-card-divider': 'rgba(171, 132, 73, 0.55)',
      '--template-primary-start': '#fffbe8',
      '--template-primary-end': '#f5d97a',
      '--template-primary-text': '#7a5200',
      '--template-primary-border': 'rgba(180, 141, 54, 0.5)',
      '--template-primary-soft': '#f6e7bf',
      '--template-secondary-start': '#f7efe2',
      '--template-secondary-end': '#e7d0aa',
      '--template-secondary-text': '#6c5537',
      '--template-secondary-border': '#d9c2a2',
      '--template-secondary-soft': '#f3e6d2',
      '--template-pill-start': '#b89a67',
      '--template-pill-end': '#99794a',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'dark-navy',
    label: '午夜',
    description: '深海軍藍底搭配電藍 accent，螢幕顯示強烈有衝擊感。',
    previewColors: ['#0d1b2e', '#dce8f8', '#2a78e4'],
    tokens: {
      '--template-board-bg': '#0d1b2e',
      '--template-board-surface': '#142236',
      '--template-board-surface-soft': '#0f1f30',
      '--template-board-border': 'rgba(88, 138, 210, 0.18)',
      '--template-board-border-strong': 'rgba(88, 138, 210, 0.32)',
      '--template-board-text': '#dce8f8',
      '--template-board-muted': '#7a9ec8',
      '--template-board-subtitle': '#5d88bb',
      '--template-board-shadow': 'rgba(0, 15, 40, 0.5)',
      '--template-card-bg': 'rgba(20, 38, 62, 0.80)',
      '--template-card-border': 'rgba(88, 138, 210, 0.22)',
      '--template-card-shadow': 'rgba(0, 10, 30, 0.45)',
      '--template-card-surface': 'rgba(16, 30, 50, 0.88)',
      '--template-card-surface-border': 'rgba(88, 138, 210, 0.14)',
      '--template-card-divider': 'rgba(88, 138, 210, 0.35)',
      '--template-primary-start': '#1d5eb0',
      '--template-primary-end': '#1044a0',
      '--template-primary-text': '#c8dcff',
      '--template-primary-border': 'rgba(60, 130, 240, 0.45)',
      '--template-primary-soft': 'rgba(20, 60, 140, 0.5)',
      '--template-secondary-start': '#162a4a',
      '--template-secondary-end': '#1e3860',
      '--template-secondary-text': '#a0bce0',
      '--template-secondary-border': 'rgba(80, 120, 190, 0.3)',
      '--template-secondary-soft': 'rgba(15, 30, 60, 0.5)',
      '--template-pill-start': '#2a78e4',
      '--template-pill-end': '#1558c8',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'crimson',
    label: '深玫',
    description: '深酒紅底搭配緋紅光暈，濃烈的典禮感。',
    previewColors: ['#180810', '#f8e0e8', '#b82250'],
    tokens: {
      '--template-board-bg': '#180810',
      '--template-board-surface': '#261018',
      '--template-board-surface-soft': '#1e0c14',
      '--template-board-border': 'rgba(220, 80, 120, 0.18)',
      '--template-board-border-strong': 'rgba(220, 80, 120, 0.32)',
      '--template-board-text': '#f8e0e8',
      '--template-board-muted': '#d090a8',
      '--template-board-subtitle': '#b06880',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(38, 16, 24, 0.82)',
      '--template-card-border': 'rgba(200, 70, 110, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(30, 12, 20, 0.88)',
      '--template-card-surface-border': 'rgba(200, 70, 110, 0.14)',
      '--template-card-divider': 'rgba(200, 70, 110, 0.35)',
      '--template-primary-start': '#b82250',
      '--template-primary-end': '#881840',
      '--template-primary-text': '#ffe0e8',
      '--template-primary-border': 'rgba(190, 50, 90, 0.45)',
      '--template-primary-soft': 'rgba(140, 20, 48, 0.55)',
      '--template-secondary-start': '#2a1020',
      '--template-secondary-end': '#381828',
      '--template-secondary-text': '#e8b0c8',
      '--template-secondary-border': 'rgba(160, 70, 105, 0.30)',
      '--template-secondary-soft': 'rgba(38, 16, 24, 0.50)',
      '--template-pill-start': '#c02858',
      '--template-pill-end': '#981840',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'amber',
    label: '琥珀',
    description: '深褐底搭配燒灼琥珀光，暗沉又炙熱的溫度感。',
    previewColors: ['#180e00', '#f8eed8', '#b87800'],
    tokens: {
      '--template-board-bg': '#180e00',
      '--template-board-surface': '#261800',
      '--template-board-surface-soft': '#1e1200',
      '--template-board-border': 'rgba(220, 160, 20, 0.18)',
      '--template-board-border-strong': 'rgba(220, 160, 20, 0.32)',
      '--template-board-text': '#f8eed8',
      '--template-board-muted': '#d4a850',
      '--template-board-subtitle': '#b08030',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(38, 24, 0, 0.82)',
      '--template-card-border': 'rgba(200, 148, 20, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(30, 18, 0, 0.88)',
      '--template-card-surface-border': 'rgba(200, 148, 20, 0.14)',
      '--template-card-divider': 'rgba(200, 148, 20, 0.35)',
      '--template-primary-start': '#b87800',
      '--template-primary-end': '#885800',
      '--template-primary-text': '#fff0c8',
      '--template-primary-border': 'rgba(190, 140, 20, 0.45)',
      '--template-primary-soft': 'rgba(140, 90, 0, 0.55)',
      '--template-secondary-start': '#2a1e00',
      '--template-secondary-end': '#382800',
      '--template-secondary-text': '#e8d098',
      '--template-secondary-border': 'rgba(160, 120, 20, 0.30)',
      '--template-secondary-soft': 'rgba(38, 24, 0, 0.50)',
      '--template-pill-start': '#c08010',
      '--template-pill-end': '#986000',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'forest',
    label: '墨綠',
    description: '深墨綠底搭配翠光，沉著中帶著清冽的森林感。',
    previewColors: ['#081810', '#d8f0e4', '#1e8050'],
    tokens: {
      '--template-board-bg': '#081810',
      '--template-board-surface': '#102218',
      '--template-board-surface-soft': '#0c1e14',
      '--template-board-border': 'rgba(80, 190, 120, 0.18)',
      '--template-board-border-strong': 'rgba(80, 190, 120, 0.32)',
      '--template-board-text': '#d8f0e4',
      '--template-board-muted': '#88c8a0',
      '--template-board-subtitle': '#60a878',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(16, 34, 22, 0.82)',
      '--template-card-border': 'rgba(80, 190, 120, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(12, 28, 18, 0.88)',
      '--template-card-surface-border': 'rgba(80, 190, 120, 0.14)',
      '--template-card-divider': 'rgba(80, 190, 120, 0.35)',
      '--template-primary-start': '#1e8050',
      '--template-primary-end': '#146038',
      '--template-primary-text': '#c8f0d8',
      '--template-primary-border': 'rgba(50, 180, 100, 0.45)',
      '--template-primary-soft': 'rgba(20, 90, 52, 0.55)',
      '--template-secondary-start': '#142a1c',
      '--template-secondary-end': '#1c3826',
      '--template-secondary-text': '#a0d8b4',
      '--template-secondary-border': 'rgba(60, 150, 90, 0.30)',
      '--template-secondary-soft': 'rgba(16, 34, 22, 0.50)',
      '--template-pill-start': '#28a060',
      '--template-pill-end': '#1a7844',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'navy-orange',
    label: '蒼橙',
    description: '深海軍藍底 × 電橙，藍橙補色對比強烈如電影海報。',
    previewColors: ['#080f1e', '#ffe8d0', '#d86800'],
    tokens: {
      '--template-board-bg': '#080f1e',
      '--template-board-surface': '#101c30',
      '--template-board-surface-soft': '#0c1828',
      '--template-board-border': 'rgba(240, 120, 20, 0.18)',
      '--template-board-border-strong': 'rgba(240, 120, 20, 0.32)',
      '--template-board-text': '#ffe8d0',
      '--template-board-muted': '#d07838',
      '--template-board-subtitle': '#b05a18',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(16, 28, 48, 0.82)',
      '--template-card-border': 'rgba(220, 110, 20, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(12, 22, 40, 0.88)',
      '--template-card-surface-border': 'rgba(220, 110, 20, 0.14)',
      '--template-card-divider': 'rgba(220, 110, 20, 0.35)',
      '--template-primary-start': '#d86800',
      '--template-primary-end': '#a85000',
      '--template-primary-text': '#ffe8c0',
      '--template-primary-border': 'rgba(210, 120, 20, 0.45)',
      '--template-primary-soft': 'rgba(170, 80, 10, 0.55)',
      '--template-secondary-start': '#101c2c',
      '--template-secondary-end': '#182a3e',
      '--template-secondary-text': '#e8b880',
      '--template-secondary-border': 'rgba(180, 100, 20, 0.30)',
      '--template-secondary-soft': 'rgba(16, 28, 48, 0.50)',
      '--template-pill-start': '#e07010',
      '--template-pill-end': '#b85000',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'purple-amber',
    label: '紫曜',
    description: '深墨紫底 × 燃黃琥珀，紫黃補色最奢華的爆炸感。',
    previewColors: ['#100a1e', '#fff0c8', '#c8a000'],
    tokens: {
      '--template-board-bg': '#100a1e',
      '--template-board-surface': '#1c1030',
      '--template-board-surface-soft': '#160c28',
      '--template-board-border': 'rgba(220, 180, 20, 0.18)',
      '--template-board-border-strong': 'rgba(220, 180, 20, 0.32)',
      '--template-board-text': '#fff0c8',
      '--template-board-muted': '#c8a038',
      '--template-board-subtitle': '#a07e20',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(28, 16, 48, 0.82)',
      '--template-card-border': 'rgba(200, 160, 20, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(22, 12, 38, 0.88)',
      '--template-card-surface-border': 'rgba(200, 160, 20, 0.14)',
      '--template-card-divider': 'rgba(200, 160, 20, 0.35)',
      '--template-primary-start': '#c8a000',
      '--template-primary-end': '#a07800',
      '--template-primary-text': '#fff8d0',
      '--template-primary-border': 'rgba(200, 160, 20, 0.45)',
      '--template-primary-soft': 'rgba(150, 115, 0, 0.55)',
      '--template-secondary-start': '#1e1030',
      '--template-secondary-end': '#2a1840',
      '--template-secondary-text': '#e8d090',
      '--template-secondary-border': 'rgba(170, 140, 20, 0.30)',
      '--template-secondary-soft': 'rgba(28, 16, 48, 0.50)',
      '--template-pill-start': '#d4a810',
      '--template-pill-end': '#a88000',
      '--template-pill-text': '#ffffff',
    },
  },
]

const CLASS_RANKING_THEMES: readonly TemplateThemeDefinition[] = [
  {
    id: 'gold',
    label: '榮耀金',
    description: '更強烈的金色層次，拉高榜單表揚感與焦點。',
    previewColors: ['#fff8e2', '#3c2b14', '#d9aa45'],
    tokens: {
      '--template-board-bg': '#fff8e2',
      '--template-board-surface': '#fffef8',
      '--template-board-surface-soft': '#fff2cb',
      '--template-board-border': '#e7d19b',
      '--template-board-border-strong': '#d7b86b',
      '--template-board-text': '#3c2b14',
      '--template-board-muted': '#8d6c41',
      '--template-board-subtitle': '#bb8f44',
      '--template-board-shadow': 'rgba(96, 67, 21, 0.1)',
      '--template-card-bg': 'rgba(255, 255, 255, 0.72)',
      '--template-card-border': 'rgba(161, 119, 34, 0.2)',
      '--template-card-shadow': 'rgba(96, 67, 21, 0.08)',
      '--template-card-surface': 'rgba(255, 249, 233, 0.94)',
      '--template-card-surface-border': 'rgba(170, 128, 49, 0.14)',
      '--template-card-divider': 'rgba(201, 151, 53, 0.68)',
      '--template-primary-start': '#f6d476',
      '--template-primary-end': '#d9aa45',
      '--template-primary-text': '#4f360d',
      '--template-primary-border': 'rgba(132, 93, 24, 0.22)',
      '--template-primary-soft': '#f9e5a8',
      '--template-secondary-start': '#f5dfb0',
      '--template-secondary-end': '#e5bf76',
      '--template-secondary-text': '#694a12',
      '--template-secondary-border': 'rgba(155, 116, 37, 0.18)',
      '--template-secondary-soft': '#faeac5',
      '--template-pill-start': '#d0a048',
      '--template-pill-end': '#ad7d22',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'emerald-night',
    label: '翡翠夜',
    description: '深墨綠底搭配翠綠 accent，沉穩又帶神秘感。',
    previewColors: ['#0a1f14', '#d8f0e4', '#28a060'],
    tokens: {
      '--template-board-bg': '#0a1f14',
      '--template-board-surface': '#122a1c',
      '--template-board-surface-soft': '#0f2318',
      '--template-board-border': 'rgba(80, 180, 120, 0.18)',
      '--template-board-border-strong': 'rgba(80, 180, 120, 0.32)',
      '--template-board-text': '#d8f0e4',
      '--template-board-muted': '#6aaa88',
      '--template-board-subtitle': '#4e9a72',
      '--template-board-shadow': 'rgba(0, 20, 10, 0.5)',
      '--template-card-bg': 'rgba(18, 42, 28, 0.80)',
      '--template-card-border': 'rgba(80, 180, 120, 0.22)',
      '--template-card-shadow': 'rgba(0, 20, 10, 0.45)',
      '--template-card-surface': 'rgba(14, 34, 22, 0.88)',
      '--template-card-surface-border': 'rgba(80, 180, 120, 0.14)',
      '--template-card-divider': 'rgba(80, 180, 120, 0.35)',
      '--template-primary-start': '#1d7a48',
      '--template-primary-end': '#0e6038',
      '--template-primary-text': '#c8f0d8',
      '--template-primary-border': 'rgba(50, 180, 100, 0.45)',
      '--template-primary-soft': 'rgba(20, 80, 45, 0.5)',
      '--template-secondary-start': '#162e1e',
      '--template-secondary-end': '#1e3e28',
      '--template-secondary-text': '#90d0a8',
      '--template-secondary-border': 'rgba(60, 150, 90, 0.3)',
      '--template-secondary-soft': 'rgba(15, 38, 25, 0.5)',
      '--template-pill-start': '#28a060',
      '--template-pill-end': '#1a8048',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'teal',
    label: '青碧',
    description: '深黑藍底搭配電青光暈，冷冽又銳利的現代感。',
    previewColors: ['#041818', '#d0f2ee', '#0ea898'],
    tokens: {
      '--template-board-bg': '#041818',
      '--template-board-surface': '#0a2424',
      '--template-board-surface-soft': '#071e1e',
      '--template-board-border': 'rgba(20, 200, 180, 0.18)',
      '--template-board-border-strong': 'rgba(20, 200, 180, 0.32)',
      '--template-board-text': '#d0f2ee',
      '--template-board-muted': '#6ad4c4',
      '--template-board-subtitle': '#48b8a8',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(10, 36, 36, 0.82)',
      '--template-card-border': 'rgba(20, 190, 170, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(7, 28, 28, 0.88)',
      '--template-card-surface-border': 'rgba(20, 190, 170, 0.14)',
      '--template-card-divider': 'rgba(20, 190, 170, 0.35)',
      '--template-primary-start': '#0ea898',
      '--template-primary-end': '#0a8878',
      '--template-primary-text': '#d0f2ee',
      '--template-primary-border': 'rgba(20, 175, 158, 0.45)',
      '--template-primary-soft': 'rgba(10, 130, 115, 0.55)',
      '--template-secondary-start': '#0e2828',
      '--template-secondary-end': '#183838',
      '--template-secondary-text': '#a0e8da',
      '--template-secondary-border': 'rgba(20, 150, 138, 0.30)',
      '--template-secondary-soft': 'rgba(10, 36, 36, 0.50)',
      '--template-pill-start': '#18b8a8',
      '--template-pill-end': '#0a9888',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'violet',
    label: '紫晶',
    description: '深黑紫底搭配電紫光暈，濃烈神秘最易辨識。',
    previewColors: ['#100818', '#eed8ff', '#7c3ae8'],
    tokens: {
      '--template-board-bg': '#100818',
      '--template-board-surface': '#1c1028',
      '--template-board-surface-soft': '#160c20',
      '--template-board-border': 'rgba(160, 80, 240, 0.18)',
      '--template-board-border-strong': 'rgba(160, 80, 240, 0.32)',
      '--template-board-text': '#eed8ff',
      '--template-board-muted': '#c090e8',
      '--template-board-subtitle': '#a068d0',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-bg': 'rgba(28, 16, 40, 0.82)',
      '--template-card-border': 'rgba(150, 70, 230, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.45)',
      '--template-card-surface': 'rgba(22, 12, 32, 0.88)',
      '--template-card-surface-border': 'rgba(150, 70, 230, 0.14)',
      '--template-card-divider': 'rgba(150, 70, 230, 0.35)',
      '--template-primary-start': '#7c3ae8',
      '--template-primary-end': '#5e20d0',
      '--template-primary-text': '#eed8ff',
      '--template-primary-border': 'rgba(140, 60, 230, 0.45)',
      '--template-primary-soft': 'rgba(90, 30, 170, 0.55)',
      '--template-secondary-start': '#201030',
      '--template-secondary-end': '#2c1840',
      '--template-secondary-text': '#d0a8f8',
      '--template-secondary-border': 'rgba(130, 70, 210, 0.30)',
      '--template-secondary-soft': 'rgba(28, 16, 40, 0.50)',
      '--template-pill-start': '#8848f0',
      '--template-pill-end': '#6e2cd8',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'graphite',
    label: '石墨',
    description: '純黑底搭配冷灰光，極致簡約讓排名本身說話。',
    previewColors: ['#0c0c0c', '#f0f0f0', '#484848'],
    tokens: {
      '--template-board-bg': '#0c0c0c',
      '--template-board-surface': '#181818',
      '--template-board-surface-soft': '#141414',
      '--template-board-border': 'rgba(200, 200, 200, 0.14)',
      '--template-board-border-strong': 'rgba(200, 200, 200, 0.26)',
      '--template-board-text': '#f0f0f0',
      '--template-board-muted': '#a8a8a8',
      '--template-board-subtitle': '#808080',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.6)',
      '--template-card-bg': 'rgba(24, 24, 24, 0.82)',
      '--template-card-border': 'rgba(180, 180, 180, 0.16)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-surface': 'rgba(18, 18, 18, 0.88)',
      '--template-card-surface-border': 'rgba(180, 180, 180, 0.10)',
      '--template-card-divider': 'rgba(180, 180, 180, 0.25)',
      '--template-primary-start': '#383838',
      '--template-primary-end': '#282828',
      '--template-primary-text': '#f0f0f0',
      '--template-primary-border': 'rgba(180, 180, 180, 0.30)',
      '--template-primary-soft': 'rgba(52, 52, 52, 0.60)',
      '--template-secondary-start': '#202020',
      '--template-secondary-end': '#2c2c2c',
      '--template-secondary-text': '#d0d0d0',
      '--template-secondary-border': 'rgba(160, 160, 160, 0.20)',
      '--template-secondary-soft': 'rgba(24, 24, 24, 0.50)',
      '--template-pill-start': '#484848',
      '--template-pill-end': '#303030',
      '--template-pill-text': '#f0f0f0',
    },
  },
  {
    id: 'teal-red',
    label: '赤夜',
    description: '深黑青底 × 烈焰紅，青紅補色最極端的視覺張力。',
    previewColors: ['#040c10', '#ffe0d8', '#e03030'],
    tokens: {
      '--template-board-bg': '#040c10',
      '--template-board-surface': '#0a1820',
      '--template-board-surface-soft': '#071218',
      '--template-board-border': 'rgba(240, 60, 40, 0.18)',
      '--template-board-border-strong': 'rgba(240, 60, 40, 0.32)',
      '--template-board-text': '#ffe0d8',
      '--template-board-muted': '#e08070',
      '--template-board-subtitle': '#c05848',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.55)',
      '--template-card-bg': 'rgba(10, 24, 32, 0.82)',
      '--template-card-border': 'rgba(220, 60, 40, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.5)',
      '--template-card-surface': 'rgba(7, 18, 24, 0.88)',
      '--template-card-surface-border': 'rgba(220, 60, 40, 0.14)',
      '--template-card-divider': 'rgba(220, 60, 40, 0.35)',
      '--template-primary-start': '#d83020',
      '--template-primary-end': '#b02010',
      '--template-primary-text': '#ffe0d8',
      '--template-primary-border': 'rgba(210, 60, 40, 0.45)',
      '--template-primary-soft': 'rgba(160, 30, 20, 0.55)',
      '--template-secondary-start': '#0e1e28',
      '--template-secondary-end': '#162a36',
      '--template-secondary-text': '#f0b0a0',
      '--template-secondary-border': 'rgba(180, 60, 40, 0.30)',
      '--template-secondary-soft': 'rgba(10, 24, 32, 0.50)',
      '--template-pill-start': '#e03828',
      '--template-pill-end': '#b82010',
      '--template-pill-text': '#ffffff',
    },
  },
  {
    id: 'neon-cyan',
    label: '霓青',
    description: '近純黑底 × 霓虹青綠，最強對比賽博龐克感。',
    previewColors: ['#020e0c', '#c8fff8', '#00c8a0'],
    tokens: {
      '--template-board-bg': '#020e0c',
      '--template-board-surface': '#081816',
      '--template-board-surface-soft': '#061210',
      '--template-board-border': 'rgba(0, 230, 180, 0.18)',
      '--template-board-border-strong': 'rgba(0, 230, 180, 0.32)',
      '--template-board-text': '#c8fff8',
      '--template-board-muted': '#48e0c0',
      '--template-board-subtitle': '#28c0a0',
      '--template-board-shadow': 'rgba(0, 0, 0, 0.6)',
      '--template-card-bg': 'rgba(8, 24, 22, 0.82)',
      '--template-card-border': 'rgba(0, 210, 160, 0.22)',
      '--template-card-shadow': 'rgba(0, 0, 0, 0.55)',
      '--template-card-surface': 'rgba(6, 18, 16, 0.88)',
      '--template-card-surface-border': 'rgba(0, 210, 160, 0.14)',
      '--template-card-divider': 'rgba(0, 210, 160, 0.35)',
      '--template-primary-start': '#00c8a0',
      '--template-primary-end': '#00a880',
      '--template-primary-text': '#d0fff8',
      '--template-primary-border': 'rgba(0, 200, 160, 0.45)',
      '--template-primary-soft': 'rgba(0, 140, 110, 0.55)',
      '--template-secondary-start': '#081e1a',
      '--template-secondary-end': '#102a26',
      '--template-secondary-text': '#80e8d0',
      '--template-secondary-border': 'rgba(0, 170, 140, 0.30)',
      '--template-secondary-soft': 'rgba(8, 24, 22, 0.50)',
      '--template-pill-start': '#00d0a8',
      '--template-pill-end': '#00a880',
      '--template-pill-text': '#0a1e18',
    },
  },
]

export const TEMPLATE_STYLE_REGISTRY: Readonly<Record<TemplateId, TemplateStyleDefinition>> = {
  'exam-result': {
    id: 'exam-result',
    label: '大考成績榜',
    defaultThemeId: 'classic',
    fontRoles: EXAM_RESULT_FONT_ROLES,
    themes: EXAM_RESULT_THEMES,
  },
  'class-ranking': {
    id: 'class-ranking',
    label: '班排榮譽榜',
    defaultThemeId: 'gold',
    fontRoles: CLASS_RANKING_FONT_ROLES,
    themes: CLASS_RANKING_THEMES,
  },
}

export function getTemplateStyleDefinition(templateId: TemplateId): TemplateStyleDefinition {
  return TEMPLATE_STYLE_REGISTRY[templateId]
}
